# Generated by Django 5.1.6 on 2025-02-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Grain', 'Grain'), ('Other', 'Other')], max_length=50)),
                ('shelf_life_days', models.IntegerField(help_text='Number of days before spoilage')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity in kilograms or units')),
                ('stored_date', models.DateField(auto_now_add=True)),
                ('shelf_date', models.DateField(help_text='Expected date of spoilage')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpoilageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spoilage', to='inventory.inventory')),
            ],
        ),
    ]
