# Generated by Django 5.1.6 on 2025-02-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sold_quantity',
            field=models.FloatField(default=0, help_text='Total quantity sold'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Liter'), ('unit', 'Unit')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(help_text='Total quantity available'),
        ),
    ]
