# Generated by Django 5.1.6 on 2025-02-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_sold_quantity_inventory_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='shelf_life_days',
            field=models.IntegerField(default=10, help_text='Number of days before spoilage'),
        ),
    ]
